import fs from 'node:fs';
import path from 'node:path';

const source = fs.readFileSync(new URL('../docs/guia-pedagogica.md', import.meta.url), 'utf8');
const output = new URL('../public/guia-helicoptero-3gdl.pdf', import.meta.url);
const clean=(text)=>text.replace(/\*\*/g,'').replace(/`/g,'').replace(/α/g,'alpha').replace(/β/g,'beta').replace(/γ/g,'gamma').replace(/ξ/g,'xi').replace(/̇/g,'_dot').replace(/ₑ/g,'_e').replace(/ᵢ/g,'_i').replace(/ᵀ/g,'^T').replace(/→/g,'->').replace(/−/g,'-').replace(/≈/g,'~').replace(/≤/g,'<=').replace(/≥/g,'>=').replace(/·/g,'-').replace(/∫/g,'Integral ').replace(/²/g,'^2').replace(/√/g,'sqrt').replace(/Δ/g,'Delta').replace(/φ/g,'phi').replace(/λ/g,'lambda').replace(/η/g,'eta').replace(/̂/g,'_hat').replace(/₀/g,'0').replace(/₁/g,'1').replace(/₂/g,'2').replace(/₃/g,'3').replace(/\[|\]/g,'').replace(/\\/g,'/');
function paragraphLines(md){const out=[];for(const raw of md.split(/\r?\n/)){const line=raw.trimEnd();if(!line.trim()){out.push({type:'space',text:''});continue;}if(/^#{1,3}\s/.test(line)){const level=(line.match(/^#+/)||['#'])[0].length;out.push({type:'h'+level,text:clean(line.replace(/^#{1,3}\s+/,''))});continue;}if(/^\|[-:| ]+\|?$/.test(line))continue;if(line.startsWith('|')){const cells=line.split('|').slice(1,-1).map(x=>clean(x.trim())).filter(Boolean);if(cells.length)out.push({type:'table',text:cells.join('  |  ')});continue;}if(/^[-*]\s+/.test(line)){out.push({type:'bullet',text:clean(line.replace(/^[-*]\s+/,''))});continue;}if(/^\d+\.\s+/.test(line)){out.push({type:'bullet',text:clean(line.replace(/^\d+\.\s+/,''))});continue;}out.push({type:'p',text:clean(line)});}return out;}
const blocks=paragraphLines(source);const W=595.28,H=841.89,margin=48,footerY=28,pages=[];let page=[],y=H-58;
const wrap=(text,size,indent=0)=>{const max=Math.max(20,Math.floor((W-2*margin-indent)/(size*.50))),words=text.split(/\s+/).filter(Boolean),lines=[];let line='';for(const word of words){if(!line){line=word;continue;}if((line+' '+word).length<=max)line+=' '+word;else{lines.push(line);line=word;}}if(line)lines.push(line);return lines.length?lines:[''];};
const newPage=()=>{if(page.length)pages.push(page);page=[];y=H-58;};
for(const b of blocks){if(b.type==='space'){y-=4;continue;}const size=b.type==='h1'?17:b.type==='h2'?13:b.type==='h3'?11:9.5,leading=size*(b.type.startsWith('h')?1.35:1.38),indent=b.type==='bullet'?13:0,lines=wrap((b.type==='bullet'?'- ':'')+b.text,size,indent),need=lines.length*leading+(b.type.startsWith('h')?9:3);if((b.type==='h1'&&page.length>5)||y-need<footerY+28)newPage();if(b.type.startsWith('h'))y-=4;for(const line of lines){page.push({x:margin+indent,y,text:line,size,bold:b.type.startsWith('h')||b.type==='table'});y-=leading;}y-=b.type.startsWith('h')?6:2;}newPage();
const esc=s=>s.replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');const objs=[];const add=s=>{objs.push(s);return objs.length;};const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>'),bold=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>'),contentIds=[],pageIds=[];
for(let i=0;i<pages.length;i++){let c='';for(const item of pages[i])c+='BT /'+(item.bold?'F2':'F1')+' '+item.size.toFixed(1)+' Tf 1 0 0 1 '+item.x.toFixed(1)+' '+item.y.toFixed(1)+' Tm ('+esc(item.text)+') Tj ET\n';c+='BT /F1 8 Tf 1 0 0 1 '+margin+' 20 Tm (Helicoptero 3 GDL - Guia pedagogica) Tj ET\n';c+='BT /F1 8 Tf 1 0 0 1 '+(W-90).toFixed(1)+' 20 Tm ('+(i+1)+' / '+pages.length+') Tj ET\n';const buf=Buffer.from(c,'latin1');contentIds.push(add('<< /Length '+buf.length+' >>\nstream\n'+c+'endstream'));pageIds.push(add('PENDING'));}
const pagesId=add('PAGES_PENDING');for(let i=0;i<pageIds.length;i++)objs[pageIds[i]-1]='<< /Type /Page /Parent '+pagesId+' 0 R /MediaBox [0 0 '+W+' '+H+'] /Resources << /Font << /F1 '+font+' 0 R /F2 '+bold+' 0 R >> >> /Contents '+contentIds[i]+' 0 R >>';objs[pagesId-1]='<< /Type /Pages /Count '+pageIds.length+' /Kids ['+pageIds.map(id=>id+' 0 R').join(' ')+'] >>';const catalog=add('<< /Type /Catalog /Pages '+pagesId+' 0 R >>');let chunks=[Buffer.from('%PDF-1.4\n%\xE2\xE3\xCF\xD3\n','latin1')],offsets=[0],offset=chunks[0].length;for(let i=0;i<objs.length;i++){offsets.push(offset);const b=Buffer.from((i+1)+' 0 obj\n'+objs[i]+'\nendobj\n','latin1');chunks.push(b);offset+=b.length;}const xref=offset;let trailer='xref\n0 '+(objs.length+1)+'\n0000000000 65535 f \n';for(let i=1;i<offsets.length;i++)trailer+=String(offsets[i]).padStart(10,'0')+' 00000 n \n';trailer+='trailer\n<< /Size '+(objs.length+1)+' /Root '+catalog+' 0 R >>\nstartxref\n'+xref+'\n%%EOF\n';chunks.push(Buffer.from(trailer,'latin1'));fs.writeFileSync(output,Buffer.concat(chunks));console.log('Generated '+path.basename(output.pathname)+': '+pages.length+' pages');
