import{useEffect,useRef,useState}from'react';
import Viewer from'./Viewer';import Charts from'./Charts';import{request,download}from'./client';import{signalCSV,summarize}from'./reporting';
import type{Config,Row,Metrics,Run,Reply,Experiment,Change}from'./types';
const controllers:Record<string,string>={state:'uₑ + K(xd − x)',prefilter:'uₑ − Kδx + Nr',integral:'uₑ − Kδx + Kiξ',smc:'Modos deslizantes',nonlinear:'Asignación no lineal',pid:'PID en cascada'};
const notes:Record<string,string>={state:'Sin feedforward adicional: útil para evidenciar qué canales parecen integradores.',prefilter:'Usa el equilibrio del modelo nominal; preciso cuando modelo y planta coinciden.',integral:'Integra errores de β y γ para rechazar sesgos y perturbaciones constantes.',smc:'Exploración robusta en cascada con capa límite.',nonlinear:'Referencia no lineal para comparar.',pid:'Referencia clásica en cascada.'};
const observers:Record<string,string>={exact:'Estados exactos',filtered:'Derivada filtrada',luenberger:'Luenberger local',ekf:'EKF'};
function Numeric({label,value,min,max,step=.1,onChange,unit=''}:{label:string;value:number;min:number;max:number;step?:number;onChange:(v:number)=>void;unit?:string}){return <label className="numeric"><span>{label}</span><div><input aria-label={label+' · valor'} type="number" min={min} max={max} step={step} value={value} onChange={e=>e.target.value!==''&&onChange(+e.target.value)}/><small>{unit}</small></div><input aria-label={label} type="range" min={min} max={max} step="any" value={value} onChange={e=>onChange(+e.target.value)}/></label>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>}
function Select({label,value,options,onChange}:{label:string;value:string;options:Record<string,string>;onChange:(v:string)=>void}){return <label className="select"><span>{label}</span><select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(options).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>}
const blank:Metrics={rmse:[0,0],estimation:[0,0,0,0,0,0],saturation:0,effort:0,waypoints:[]};
export default function App(){
 const[config,setConfig]=useState<Config>();const base=useRef<Config|undefined>(undefined);const applied=useRef<Config|undefined>(undefined);const initial=useRef<Config|undefined>(undefined);const events=useRef<Change[]>([]);const busy=useRef(false);
 const[rows,setRows]=useState<Row[]>([]);const[metrics,setMetrics]=useState(blank);const[running,setRunning]=useState(false);const[ready,setReady]=useState(false);const[status,setStatus]=useState('Cargando motor Python…');const[error,setError]=useState('');const[tab,setTab]=useState('control');const[advanced,setAdvanced]=useState(false);const[cursor,setCursor]=useState(0);const[follow,setFollow]=useState(true);const[speed,setSpeed]=useState(1);const[runs,setRuns]=useState<Run[]>([]);const[selected,setSelected]=useState<string[]>([]);
 async function reset(c:Config){setRunning(false);setReady(false);busy.current=true;try{const r=await request<Reply>({op:'reset',config:c,events:[]});const accepted=r.config!;initial.current=structuredClone(accepted);applied.current=structuredClone(accepted);events.current=[];setConfig(accepted);setRows(r.rows);setMetrics(r.metrics);setCursor(0);setFollow(true);setReady(true);setError('');setStatus('Listo para explorar');}catch(e){setError(String(e));setStatus('Configuración no válida');if(applied.current){setConfig(structuredClone(applied.current));setReady(true)}}finally{busy.current=false;}}
 useEffect(()=>{void(async()=>{try{const c=await request<Config>({op:'defaults'});base.current=structuredClone(c);await reset(c)}catch(e){setError(String(e));setStatus('No se pudo cargar el motor')}})()},[]);
 useEffect(()=>{if(!config||!ready||JSON.stringify(config)===JSON.stringify(applied.current))return;const timer=setTimeout(async()=>{const previous=applied.current!;if(['controller','gainMethod','observer','dt','seed','initial','plantModel','trim'].some(k=>JSON.stringify(config[k as keyof Config])!==JSON.stringify(previous[k as keyof Config]))){await reset(config);return}busy.current=true;try{const r=await request<{config:Config;event:Change;events:Change[]}>({op:'update',config});applied.current=structuredClone(r.config);events.current=r.events;setError('');setStatus('Cambio aplicado en t = '+r.event.time.toFixed(2)+' s')}catch(e){setConfig(structuredClone(previous));setError(String(e))}finally{busy.current=false}},250);return()=>clearTimeout(timer)},[config,ready]);
 async function advance(n=1){if(busy.current||!ready)return;busy.current=true;try{const r=await request<Reply>({op:'advance',n});setRows(old=>[...old,...r.rows]);setMetrics(r.metrics);if(r.stopped){setRunning(false);setStatus(r.reason)}else if(running)setStatus('Simulación en curso')}catch(e){setRunning(false);setError(String(e))}finally{busy.current=false}}
 useEffect(()=>{if(!running||!config)return;const timer=setInterval(()=>void advance(Math.max(1,Math.round(.1*speed/config.dt))),100);return()=>clearInterval(timer)},[running,config?.dt,speed,ready]);useEffect(()=>{if(follow)setCursor(Math.max(0,rows.length-1))},[rows,follow]);
 function edit(f:(c:Config)=>void){setConfig(old=>{if(!old)return old;const c=structuredClone(old);if(old.linked)c.nominal=structuredClone(old.params);f(c);if(c.linked)c.nominal=structuredClone(c.params);return c})}function value<K extends keyof Config>(k:K,v:Config[K]){edit(c=>{c[k]=v})}function arr(k:keyof Config,i:number,v:number){edit(c=>{((c[k] as unknown)as number[])[i]=v})}
 function scenario(kind:string){edit(c=>{const b=base.current!;c.params=structuredClone(b.params);c.nominal=structuredClone(b.params);c.linked=true;Object.assign(c.flags,{coulomb:false,counterweight:false,constantDisturbance:false,disturbance:false,saturation:false,deadzone:false,delay:false,measurement:false,process:false});c.counterweightBias=0;c.constantDisturbance=[0,0,0];if(kind==='bias'){c.flags.counterweight=true;c.counterweightBias=1.5}if(kind==='friction')c.flags.coulomb=true;if(kind==='constant'){c.flags.constantDisturbance=true;c.constantDisturbance=[.15,.8,.35]}if(kind==='real'){Object.assign(c.flags,{coulomb:true,counterweight:true,constantDisturbance:true,saturation:true,deadzone:true,delay:true});c.counterweightBias=1;c.constantDisturbance=[.1,.5,.2];c.linked=false;c.params.a_alpha*=.9;c.params.a_psi*=.9}})}
 if(!config)return <main className="loading"><div className="logo">H<span>3</span></div><h1>Helicóptero · 3 GDL</h1><p>{status}</p>{error&&<pre>{error}</pre>}</main>;
 const row=rows[cursor]??rows.at(-1),summary=summarize(rows),compared=runs.filter(r=>selected.includes(r.id)),linear=['state','prefilter','integral'].includes(config.controller);const points:[string,number,number][]=[['D',0,0],['A',-45,-45],['B',-45,45],['C',45,0]];const list=(k:keyof Config,names:string[],min:number,max:number,step=.1)=>names.map((n,i)=><Numeric key={n} label={n} value={((config[k] as unknown)as number[])[i]} min={min} max={max} step={step} onChange={v=>arr(k,i,v)}/>);
 const exp=():Experiment=>({version:1,config:initial.current!,events:events.current});
 function save(){const run:Run={id:crypto.randomUUID(),name:controllers[config!.controller]+' · '+(runs.length+1),experiment:exp(),rows:[...rows],metrics};setRuns(old=>[...old,run])}
 return <main>
  <header className="top"><div className="brand"><div className="logo">H<span>3</span></div><div><span className="eyebrow">LABORATORIO INTERACTIVO · CONTROL AVANZADO</span><h1>Helicóptero <span>3 GDL</span></h1></div></div><div className="header-actions"><a className="guide-link" href="./guia-helicoptero-3gdl.pdf" target="_blank" rel="noreferrer">Guía PDF ↗</a><span className={'status-pill '+(running?'live':'')}><i className="dot teal"/>{running?'En ejecución':'Listo'}</span><button onClick={()=>void reset(initial.current!)}>↺ Reiniciar</button></div></header>
  <div className="convention-strip"><b>Convención</b><span>α · roll (+ mano derecha sobre +x)</span><span>β · pitch (+ motores hacia abajo)</span><span>γ · yaw (+ alrededor de +z)</span><small>x adelante · y izquierda · z arriba</small></div>
  <section className="scenario-bar card"><div><span className="eyebrow">ESCENARIOS</span><strong>Cambia una condición y compara</strong></div><div className="scenario-buttons">{[['ideal','Ideal'],['bias','Contrapeso'],['friction','Coulomb'],['constant','Perturbación constante'],['real','Combinado']].map(([k,n])=><button key={k} onClick={()=>scenario(k)}>{n}</button>)}</div></section>
  <div className="workspace"><aside className="card side"><div className="panel-title"><span className="eyebrow">01 · CONSIGNA</span><h2>Experimento</h2><p>Define β y γ; α queda libre para producir yaw.</p></div><Select label="Referencia" value={config.reference} options={{smooth:'Setpoint suave',step:'Escalón',multipoint:'Ruta multipunto'}} onChange={v=>value('reference',v)}/><Numeric label="β deseado" value={-config.setpoint[0]} min={-60} max={60} step={1} unit="°" onChange={v=>edit(c=>{c.setpoint[0]=-v;c.reference='smooth'})}/><Numeric label="γ deseado" value={config.setpoint[1]} min={-60} max={60} step={1} unit="°" onChange={v=>edit(c=>{c.setpoint[1]=v;c.reference='smooth'})}/>{config.reference==='smooth'&&<Numeric label="Transición" value={config.transitionDuration} min={.2} max={15} step={.2} unit="s" onChange={v=>value('transitionDuration',v)}/>}<div className="quick-points">{points.map(([n,b,g])=><button key={n} onClick={()=>edit(c=>{c.setpoint=[-b,g];c.reference='smooth'})}>{n}</button>)}</div><Numeric label="Duración" value={config.duration} min={2} max={120} step={1} unit="s" onChange={v=>value('duration',v)}/></aside>
   <div className="center"><Viewer row={row} observer={config.observer} rows={rows}/><div className="transport card"><button className="primary" disabled={!ready} onClick={()=>{setFollow(true);setRunning(v=>!v)}}>{running?'Ⅱ Pausar':'▶ Iniciar'}</button><button disabled={running||!ready} onClick={()=>{setFollow(true);void advance()}}>＋ Paso</button><select aria-label="Velocidad de reproducción" value={speed} onChange={e=>setSpeed(+e.target.value)}>{[.5,1,2,4].map(v=><option key={v} value={v}>{v}×</option>)}</select><span>Δt = {config.dt.toFixed(3)} s</span></div><div className="status-line">{status}</div>{row?.limited&&<div className="warning">Límite de asignación de roll.</div>}{row?.saturated&&<div className="warning">Actuador saturado.</div>}{error&&<div className="error">{error}</div>}</div>
   <aside className="card side"><div className="panel-title"><span className="eyebrow">02 · SISTEMA</span><h2>Control y realidad</h2><p>La teoría y los protocolos están en la guía PDF.</p></div><div className="system-tabs" role="tablist">{[['control','Control'],['effects','No idealidades'],['observer','Estimación']].map(([k,n])=><button key={k} role="tab" aria-selected={tab===k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{n}</button>)}</div>
    {tab==='control'&&<><Select label="Ley de control" value={config.controller} options={controllers} onChange={v=>value('controller',v)}/><p className="info-note control-note">{notes[config.controller]}</p>{linear&&<><Select label="Diseño de K" value={config.gainMethod} options={{lqr:'LQR',poles:'Ubicación de polos'}} onChange={v=>value('gainMethod',v)}/><Numeric label="β de operación" value={-config.trim} min={-50} max={50} step={1} unit="°" onChange={v=>value('trim',-v)}/><p className="muted">β=0° puede perder autoridad local sobre yaw.</p>{config.gainMethod==='lqr'&&<details><summary>Pesos LQR</summary>{list('lqrQ',['Q β','Q β̇','Q α','Q α̇','Q γ','Q γ̇'],.001,100,.5)}{list('lqrR',['R colectivo','R diferencial'],.001,10,.1)}{config.controller==='integral'&&<Numeric label="Peso integral" value={config.integralWeight} min={.01} max={100} onChange={v=>value('integralWeight',v)}/>}</details>}{config.gainMethod==='poles'&&<details><summary>Polos continuos</summary>{list(config.controller==='integral'?'integralPoles':'desiredPoles',Array.from({length:config.controller==='integral'?8:6},(_,i)=>'p'+(i+1)),-20,-.01,.05)}</details>}</>}{config.controller==='smc'&&<details open><summary>Parámetros SMC</summary>{list('smcLambda',['λ β','λ γ','λ α'],.05,10,.1)}{list('smcEta',['η β','η γ','η α'],.01,10,.05)}{list('smcPhi',['φ β','φ γ','φ α'],.005,.8,.01)}</details>}</>}
    {tab==='effects'&&<><Toggle label="Fricción de Coulomb + adherencia" checked={config.flags.coulomb} onChange={v=>edit(c=>{c.flags.coulomb=v})}/><Toggle label="Desbalance del contrapeso" checked={config.flags.counterweight} onChange={v=>edit(c=>{c.flags.counterweight=v})}/>{config.flags.counterweight&&<Numeric label="Sesgo β" value={config.counterweightBias} min={-5} max={5} step={.1} unit="°/s²" onChange={v=>value('counterweightBias',v)}/>}<Toggle label="Perturbación constante" checked={config.flags.constantDisturbance} onChange={v=>edit(c=>{c.flags.constantDisturbance=v})}/>{config.flags.constantDisturbance&&list('constantDisturbance',['dα','dβ','dγ'],-5,5,.05)}<details><summary>Actuadores</summary>{[['saturation','Saturación'],['deadzone','Zona muerta'],['delay','Retardo'],['disturbance','Ráfagas']].map(([k,n])=><Toggle key={k} label={n} checked={config.flags[k]} onChange={v=>edit(c=>{c.flags[k]=v})}/>)}</details><Toggle label="Modelo nominal = planta" checked={config.linked} onChange={v=>value('linked',v)}/></>}
    {tab==='observer'&&<><Select label="Realimentación" value={config.observer} options={observers} onChange={v=>value('observer',v)}/>{config.observer!=='exact'&&<Toggle label="Ruido de medición" checked={config.flags.measurement} onChange={v=>edit(c=>{c.flags.measurement=v})}/>}<p className="info-note">Primero compara controladores con estados exactos.</p></>}<div className="advanced-toggle"><Toggle label="Opciones avanzadas" checked={advanced} onChange={setAdvanced}/></div>{advanced&&<><Select label="Modelo de planta" value={config.plantModel} options={{nonlinear:'No lineal',linear:'Lineal local'}} onChange={v=>value('plantModel',v)}/><Numeric label="Paso de integración" value={config.dt} min={.005} max={.05} step={.005} unit="s" onChange={v=>value('dt',v)}/><Numeric label="Semilla" value={config.seed} min={0} max={10000} step={1} onChange={v=>value('seed',v)}/></>}</aside></div>
  <section className="evidence card"><div className="evidence-heading"><div><span className="eyebrow">03 · RESULTADOS</span><h2>Compara con evidencia</h2></div><span className="badge">{rows.length.toLocaleString()} muestras</span></div><div className="metrics">{[['RMSE β',summary?.rmse[0],'°'],['RMSE γ',summary?.rmse[1],'°'],['eβ últimos 3 s',summary?.steadyError[0],'°'],['eγ últimos 3 s',summary?.steadyError[1],'°'],['Saturación',summary?.saturation,'%']].map(([n,v,u])=><div key={String(n)}><span>{n}</span><strong>{v===undefined?'—':Number(v).toFixed(2)}<small>{u}</small></strong></div>)}</div><Charts rows={rows} runs={compared} cursor={cursor} onCursor={v=>{setRunning(false);setFollow(false);setCursor(v)}}/>{!follow&&<button className="text-button" onClick={()=>setFollow(true)}>Volver al último instante</button>}</section>
  <section className="experiments card"><div className="evidence-heading"><div><span className="eyebrow">04 · CORRIDAS</span><h2>Guardar y superponer</h2></div><div className="export-actions"><button onClick={()=>download('experimento-helicoptero.json',JSON.stringify(exp(),null,2))}>↓ JSON</button><button onClick={()=>download('senales-helicoptero.csv',signalCSV(rows),'text/csv;charset=utf-8')}>↓ CSV</button><button className="primary" onClick={save}>Guardar corrida</button></div></div>{runs.length?<div className="table-scroll"><table><thead><tr><th>Comparar</th><th>Corrida</th><th>RMSE β</th><th>RMSE γ</th></tr></thead><tbody>{runs.map(run=><tr key={run.id}><td><input type="checkbox" aria-label={'Comparar '+run.name} checked={selected.includes(run.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,run.id]:old.filter(x=>x!==run.id))}/></td><td>{run.name}</td><td>{(summarize(run.rows)?.rmse[0]??0).toFixed(2)}°</td><td>{(summarize(run.rows)?.rmse[1]??0).toFixed(2)}°</td></tr>)}</tbody></table></div>:<div className="empty">Guarda una corrida, cambia un solo factor y compárala.</div>}</section>
 </main>}
