import{useEffect,useRef,useState}from'react';
import Viewer from './Viewer';import Charts from './Charts';import{request,download,storage}from'./client';import{lessons,preset}from'./presets';
import type{Config,Row,Metrics,Run,Reply,Experiment,Change}from'./types';
const controllers:Record<string,string>={nonlinear:'No lineal · asignación',pid:'PID en cascada',lqr:'LQR · estados',lqi:'LQI · integral'};
const observers:Record<string,string>={exact:'Estados exactos',filtered:'Derivada filtrada',luenberger:'Luenberger local',ekf:'Filtro de Kalman extendido'};
const parameterLabels:Record<string,string>={a_alpha:'Autoridad de elevación',a_theta:'Autoridad de roll',a_psi:'Autoridad de yaw',k_alpha:'Restauración de elevación',k_theta:'Restauración de roll',b_alpha:'Fricción viscosa α',b_theta:'Fricción viscosa θ',b_psi:'Fricción viscosa ψ',coulomb_alpha:'Coulomb α',coulomb_theta:'Coulomb θ',coulomb_psi:'Coulomb ψ',coulomb_smoothing:'Suavizado de Coulomb',u_c_max:'Límite colectivo',u_d_max:'Límite diferencial',deadzone_c:'Zona muerta colectiva',deadzone_d:'Zona muerta diferencial',delay_seconds:'Retardo [s]'};
const effectLabels:Record<string,string>={saturation:'Saturación',deadzone:'Zona muerta',delay:'Retardo de actuación',coulomb:'Fricción de Coulomb',measurement:'Ruido de medición',process:'Ruido de proceso',disturbance:'Perturbaciones externas',compensateDeadzone:'Compensar zona muerta',compensateFriction:'Compensar fricción',compensateDelay:'Predictor de retardo · experimental'};
function Numeric({label,value,min,max,step=.1,onChange,unit=''}:{label:string;value:number;min:number;max:number;step?:number;onChange:(v:number)=>void;unit?:string}){
 return <label className="numeric"><span>{label}</span><div><input aria-label={label+' · valor'} type="number" min={min} max={max} step={step} value={value} onChange={e=>{if(e.target.value!==''&&Number.isFinite(+e.target.value))onChange(+e.target.value);}}/><small>{unit}</small></div><input aria-label={label} type="range" min={min} max={max} step="any" value={value} onChange={e=>onChange(+e.target.value)}/></label>;
}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="toggle"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>;}
function Select({label,value,options,onChange}:{label:string;value:string;options:Record<string,string>;onChange:(v:string)=>void}){return <label className="select"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(options).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label>;}
const blankMetrics:Metrics={rmse:[0,0],estimation:[0,0,0,0,0,0],saturation:0,effort:0,waypoints:[]};
function decode(hash:string):Experiment{return JSON.parse(new TextDecoder().decode(Uint8Array.from(atob(hash),c=>c.charCodeAt(0))));}
function encode(exp:Experiment){return btoa(Array.from(new TextEncoder().encode(JSON.stringify(exp)),b=>String.fromCharCode(b)).join(''));}
export default function App(){
 const[config,setConfig]=useState<Config>();const base=useRef<Config|undefined>(undefined);const applied=useRef<Config|undefined>(undefined);const initial=useRef<Config|undefined>(undefined);const events=useRef<Change[]>([]);const epoch=useRef(0);const busy=useRef(false);
 const[rows,setRows]=useState<Row[]>([]);const[metrics,setMetrics]=useState(blankMetrics);const[running,setRunning]=useState(false);const[ready,setReady]=useState(false);const[status,setStatus]=useState('Cargando motor Python…');const[error,setError]=useState('');
 const[tab,setTab]=useState('plant');const[mode,setMode]=useState('guided');const[advanced,setAdvanced]=useState(false);const[runs,setRuns]=useState<Run[]>([]);const[selected,setSelected]=useState<string[]>([]);const[cursor,setCursor]=useState(0);const[follow,setFollow]=useState(true);const[speed,setSpeed]=useState(1);const[eventCount,setEventCount]=useState(0);const[runName,setRunName]=useState('');
 const file=useRef<HTMLInputElement>(null);const replay=useRef<Change[]>([]);
 async function reset(c:Config,recorded:Change[]=[]){
  setRunning(false);setReady(false);busy.current=true;const id=++epoch.current;setStatus('Preparando experimento…');setError('');
  try{const r=await request<Reply>({op:'reset',config:c,events:recorded});if(id!==epoch.current)return;
   const accepted=r.config!;initial.current=structuredClone(accepted);applied.current=structuredClone(accepted);events.current=recorded;replay.current=recorded;setEventCount(recorded.length);setConfig(accepted);setRows(r.rows);setMetrics(r.metrics);setCursor(0);setFollow(true);setReady(true);setStatus('Listo para explorar');return true;
  }catch(e){setError(String(e));setStatus('Configuración no válida');if(applied.current){setConfig(structuredClone(applied.current));setReady(true);}return false;}finally{busy.current=false;}
 }
 useEffect(()=>{let alive=true;(async()=>{try{const c=await request<Config>({op:'defaults'});if(!alive)return;base.current=c;
   let exp:Experiment|undefined;try{if(location.hash.startsWith('#experiment='))exp=decode(location.hash.slice(12));}catch{setError('El enlace no contiene un experimento válido.');}
   if(exp&&exp.version!==1){setError('Versión del enlace no compatible.');exp=undefined;}
   const ok=await reset(exp?.config??c,exp?.events??[]);if(!ok&&exp){await reset(c);setError('El enlace contenía una configuración inválida. Se cargó el modelo perfecto.');}
   try{const saved=await storage('load');if(alive)setRuns(saved);}catch{setError('El almacenamiento local no está disponible; puedes exportar JSON.');}
  }catch(e){setError(String(e));setStatus('No se pudo cargar el motor. Comprueba tu conexión y recarga.');}})();return()=>{alive=false};},[]);
 useEffect(()=>{if(!config||!ready||JSON.stringify(config)===JSON.stringify(applied.current))return;
  const timeout=setTimeout(async()=>{
   const previous=applied.current!;
   if(['controller','observer','dt','seed','initial','plantModel'].some(k=>JSON.stringify(config[k as keyof Config])!==JSON.stringify(previous[k as keyof Config]))){await reset(config);return;}
   busy.current=true;const id=epoch.current;
   try{const result=await request<{config:Config;event:Change;events:Change[]}>({op:'update',config});if(id!==epoch.current)return;applied.current=structuredClone(result.config);events.current=result.events;replay.current=[];setEventCount(events.current.length);setError('');setStatus('Cambio aplicado en t = '+result.event.time.toFixed(2)+' s');}
   catch(e){setRunning(false);setError(String(e));setConfig(structuredClone(previous));}finally{busy.current=false;}
  },300);return()=>clearTimeout(timeout);
 },[config,ready]);
 async function advance(n=1){if(busy.current||!ready)return;busy.current=true;const id=epoch.current;
  try{const r=await request<Reply>({op:'advance',n});if(id!==epoch.current)return;setRows(old=>[...old,...r.rows]);setMetrics(r.metrics);if(replay.current.length&&r.config){applied.current=structuredClone(r.config);setConfig(r.config);events.current=r.events??events.current;}if(r.stopped){setRunning(false);setStatus(r.reason);}else if(running)setStatus('Simulación en curso');}
  catch(e){setRunning(false);setError(String(e));}finally{busy.current=false;}
 }
 useEffect(()=>{if(!running||!config)return;const timer=setInterval(()=>void advance(Math.max(1,Math.round(.1*speed/config.dt))),100);return()=>clearInterval(timer);},[running,config?.dt,speed,ready]);
 useEffect(()=>{if(follow)setCursor(Math.max(0,rows.length-1));},[rows,follow]);
 function edit(mutator:(c:Config)=>void){setConfig(old=>{if(!old)return old;const c=structuredClone(old);if(old.linked)c.nominal=structuredClone(old.params);mutator(c);if(c.linked)c.nominal=structuredClone(c.params);return c;});}
 function value<K extends keyof Config>(k:K,v:Config[K]){edit(c=>{c[k]=v;});}
 function array(k:'kp'|'kd'|'ki'|'lqrQ'|'lqrR'|'sensorStd'|'processStd'|'ekfR'|'initial',i:number,v:number){edit(c=>{c[k][i]=v;});}
 function experiment():Experiment{return{version:1,config:initial.current!,events:events.current};}
 async function save(){if(!rows.length)return;const run:Run={id:crypto.randomUUID(),name:runName.trim()||`${controllers[config!.controller]} · ${runs.length+1}`,experiment:experiment(),rows,metrics};try{await storage('put',run);setRuns(old=>[...old,run]);setRunName('');setStatus('Corrida guardada en este navegador');}catch(e){setError('No se pudo guardar: '+String(e));}}
 async function load(exp:Experiment){if(exp.version!==1||!Array.isArray(exp.events)||!exp.config)throw new Error('Formato de experimento inválido.');await reset(exp.config,exp.events);}
 async function share(){try{const url=location.origin+location.pathname+'#experiment='+encode(experiment());if(url.length>30000){download('experimento-helicoptero.json',JSON.stringify(experiment(),null,2));setStatus('Experimento extenso: se descargó el JSON para compartir.');return;}await navigator.clipboard.writeText(url);setStatus('Enlace del experimento copiado');}catch(e){setError('No se pudo copiar el enlace: '+String(e));}}
 function csv(){const header=['t_s',...['real','estimado'].flatMap(p=>['alpha','alpha_dot','theta','theta_dot','psi','psi_dot'].map(a=>`${p}_${a}_rad`)), 'ref_alpha_rad','ref_psi_rad','uc_efectivo','ud_efectivo'];download('senales-helicoptero.csv',[header.join(','),...rows.map(r=>[r.t,...r.x,...r.hat,...r.ref,...r.effective].join(','))].join('\n'),'text/csv');}
 if(!config)return <main className="loading"><div className="logo">H<span>3</span></div><h1>Helicóptero · 3 GDL</h1><p>{status}</p><p className="muted">Preparando NumPy y SciPy. La primera carga puede tardar unos segundos.</p>{error&&<pre role="alert">{error}</pre>}</main>;
 const lesson=lessons[config.level-1];const row=rows[cursor]??rows.at(-1);const compared=runs.filter(r=>selected.includes(r.id));
 const listArray=(key:'kp'|'kd'|'ki'|'lqrQ'|'lqrR'|'sensorStd'|'processStd'|'ekfR'|'initial',names:string[],max:number,min=0,step=.1)=>names.map((label,i)=><Numeric key={label} label={label} value={config[key][i]} min={min} max={max} step={step} onChange={v=>array(key,i,v)}/>);
 return <main>
  <header className="top"><div className="brand"><div className="logo">H<span>3</span></div><div><span className="eyebrow">LABORATORIO INTERACTIVO · CONTROL</span><h1>Helicóptero <span>3 GDL</span></h1></div></div><div className="header-actions"><span className={'status-pill '+(running?'live':'')}><i className="dot teal"/>{running?'En ejecución':'Laboratorio listo'}</span><button onClick={()=>void reset(initial.current!)}>↺ Restablecer</button></div></header>
  <section className="journey" aria-label="Niveles pedagógicos">{lessons.map((l,i)=><button key={l[0]} className={config.level===i+1?'selected':''} onClick={()=>void reset(preset(base.current!,i+1))}><span>{String(i+1).padStart(2,'0')}</span>{l[0]}</button>)}</section>
  <section className="lesson-strip"><div><span className="eyebrow">ETAPA {config.level} / 6</span><h2>{lesson[1]}</h2>{mode==='guided'&&<p>{lesson[2]}</p>}</div><div className="mode-switch"><button className={mode==='guided'?'active':''} onClick={()=>setMode('guided')}>Guía</button><button className={mode==='free'?'active':''} onClick={()=>setMode('free')}>Exploración libre</button></div></section>
  <div className="workspace">
   <aside className="card side"><div className="panel-title"><span className="eyebrow">01 · ENTRADAS</span><h2>Referencias</h2><p>Define el movimiento de elevación y yaw.</p></div>
    <Select label="Tipo de referencia" value={config.reference} options={{multipoint:'Trayectoria multipunto',smooth:'Setpoint · transición suave',step:'Setpoint · escalón'}} onChange={v=>value('reference',v)}/>
    {['Elevación α','Yaw ψ'].map((label,i)=><Numeric key={label} label={label} value={config.setpoint[i]} min={-60} max={60} step={1} unit="°" onChange={v=>edit(c=>{c.setpoint[i]=v;if(c.reference==='multipoint')c.reference='smooth';})}/>)}
    {config.reference==='smooth'&&<Numeric label="Duración de transición" value={config.transitionDuration} min={.2} max={15} step={.2} unit="s" onChange={v=>value('transitionDuration',v)}/>}
    <div className="quick-points">{[['D',0,0],['A',-45,-45],['B',45,-45],['C',0,45]].map(([name,y,a])=><button key={name} onClick={()=>edit(c=>{c.setpoint=[Number(a),Number(y)];c.reference='smooth';})}>{name}</button>)}</div>
    {config.reference==='multipoint'&&<><div className="section-label">RUTA · YAW / ELEVACIÓN [°]</div><div className="waypoints">{config.waypoints.map((p,i)=><div key={i}><input aria-label={`Punto ${i+1} nombre`} value={p[0]} maxLength={30} onChange={e=>edit(c=>{c.waypoints[i][0]=e.target.value;})}/>{[1,2].map(j=><input key={j} aria-label={`Punto ${i+1} ${j===1?'yaw':'elevación'}`} type="number" min={-60} max={60} value={p[j]} onChange={e=>edit(c=>{c.waypoints[i][j]=+e.target.value;})}/>)}<button aria-label={`Eliminar punto ${i+1}`} disabled={config.waypoints.length<=2} onClick={()=>edit(c=>{c.waypoints.splice(i,1);})}>×</button></div>)}</div><button className="text-button" disabled={config.waypoints.length>=30} onClick={()=>edit(c=>{c.waypoints.push(['P',0,0]);c.duration=(c.waypoints.length-1)*c.segmentDuration;})}>+ Añadir punto</button><Numeric label="Duración por tramo" value={config.segmentDuration} min={.5} max={30} step={.5} unit="s" onChange={v=>edit(c=>{c.segmentDuration=v;c.duration=v*(c.waypoints.length-1);})}/></>}
    <div className="section-label">EXPERIMENTO</div><Numeric label="Duración total" value={config.duration} min={1} max={120} step={1} unit="s" onChange={v=>value('duration',v)}/>
    <div className="info-note">θ no es un setpoint independiente: el controlador calcula el roll necesario para producir yaw.</div>
   </aside>
   <div className="center"><Viewer row={row} observer={config.observer}/><div className="transport card"><button className="primary" disabled={!ready||JSON.stringify(config)!==JSON.stringify(applied.current)} onClick={()=>{setFollow(true);setRunning(v=>!v);}}>{running?'Ⅱ Pausar':'▶ Iniciar'}</button><button disabled={running||!ready||JSON.stringify(config)!==JSON.stringify(applied.current)} onClick={()=>{setFollow(true);void advance();}}>＋ Un paso</button><select aria-label="Velocidad de reproducción" value={speed} onChange={e=>setSpeed(+e.target.value)}>{[.5,1,2,4].map(v=><option key={v} value={v}>{v}×</option>)}</select><span className="step-size">Δt = {config.dt.toFixed(3)} s</span></div><div className="status-line" role="status">{status}</div>{row?.limited&&<div className="warning">Límite de asignación: la maniobra solicita más autoridad de yaw o roll de la disponible.</div>}{row?.saturated&&<div className="warning">Actuador saturado · integración del controlador suspendida.</div>}{error&&<div className="error" role="alert">{error}</div>}{mode==='guided'&&<div className="question"><span>PARA EXPLORAR</span><p>{lesson[3]}</p><button onClick={()=>void reset(preset(base.current!,config.level))}>Cargar experimento de esta etapa ↗</button></div>}</div>
   <aside className="card side"><div className="panel-title"><span className="eyebrow">02 · CONFIGURACIÓN</span><h2>Sistema</h2><p>Una variable a la vez. Observa qué cambia.</p></div><div className="system-tabs" role="tablist" aria-label="Configuración del sistema">{[['plant','Planta'],['control','Control'],['sensor','Sensores'],['observer','Observador'],['comp','Compensación']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==='plant'&&<><Select label="Modelo de planta" value={config.plantModel} options={{nonlinear:'Dinámica no lineal',linear:'Aproximación lineal local'}} onChange={v=>value('plantModel',v)}/>{['saturation','deadzone','delay','coulomb','disturbance'].map(k=><Toggle key={k} label={effectLabels[k]} checked={config.flags[k]} onChange={v=>edit(c=>{c.flags[k]=v;})}/>)}<Toggle label="Modelo interno = planta real" checked={config.linked} onChange={v=>value('linked',v)}/><details><summary>Parámetros de la planta</summary>{Object.keys(config.params).map(k=><Numeric key={k} label={parameterLabels[k]} value={config.params[k]} min={k.startsWith('a_')||['coulomb_smoothing','u_c_max','u_d_max'].includes(k)?.001:0} max={k==='delay_seconds'?2:k.includes('deadzone')?1:10} step={k==='delay_seconds'?.02:.01} onChange={v=>edit(c=>{c.params[k]=v;})}/>)}</details>{!config.linked&&<details><summary>Parámetros del modelo interno</summary>{Object.keys(config.nominal).map(k=><Numeric key={k} label={parameterLabels[k]+' · nominal'} value={config.nominal[k]} min={k.startsWith('a_')||['coulomb_smoothing','u_c_max','u_d_max'].includes(k)?.001:0} max={k==='delay_seconds'?2:10} step={.01} onChange={v=>edit(c=>{c.nominal[k]=v;})}/>)}</details>}</>}
    {tab==='control'&&<><Select label="Arquitectura" value={config.controller} options={controllers} onChange={v=>edit(c=>{c.controller=v;if(['lqr','lqi','pid'].includes(v)){c.reference='smooth';c.initial=[c.trim,0,0,0,0,0];c.setpoint=[c.trim+2,5];}})}/>{['lqr','lqi'].includes(config.controller)?<><Numeric label="Equilibrio de elevación" value={config.trim} min={-60} max={60} step={1} unit="°" onChange={v=>value('trim',v)}/><p className="info-note">Diseño local. En 0° el empuje de equilibrio es cero y la linealización pierde autoridad sobre yaw.</p>{listArray('lqrQ',['Peso α','Peso α̇','Peso θ','Peso θ̇','Peso ψ','Peso ψ̇'],100,.001,.5)}{listArray('lqrR',['Costo colectivo','Costo diferencial'],10,.001,.1)}{config.controller==='lqi'&&<Numeric label="Peso integral" value={config.integralWeight} min={.01} max={100} onChange={v=>value('integralWeight',v)}/>}</>:<>{listArray('kp',['Kp elevación','Kp yaw','Kp roll'],40)}{listArray('kd',['Kd elevación','Kd yaw','Kd roll'],20)}{config.controller==='pid'&&listArray('ki',['Ki elevación','Ki yaw','Ki roll'],10)}{config.controller==='pid'&&<p className="info-note">PID local con feedforward gravitacional y anti-windup condicional. Cerca del empuje cero disminuye la autoridad de yaw.</p>}</>}<Numeric label="Límite de roll asignado" value={config.rollLimit} min={1} max={60} step={1} unit="°" onChange={v=>value('rollLimit',v)}/></>}
    {tab==='sensor'&&<>{['measurement','process'].map(k=><Toggle key={k} label={effectLabels[k]} checked={config.flags[k]} onChange={v=>edit(c=>{c.flags[k]=v;})}/>)}<div className="section-label">RUIDO FÍSICO · DESVIACIÓN [°]</div>{listArray('sensorStd',['Sensor α','Sensor θ','Sensor ψ'],5,0,.05)}<details><summary>Ruido de proceso · rad/s/√s</summary>{listArray('processStd',['Proceso α̇','Proceso θ̇','Proceso ψ̇'],.2,0,.002)}</details><p className="info-note">Las mismas semillas producen las mismas realizaciones de ruido, aunque cambies de controlador.</p></>}
    {tab==='observer'&&<><Select label="Fuente de realimentación" value={config.observer} options={observers} onChange={v=>value('observer',v)}/><p className="info-note">{config.observer==='exact'?'El controlador accede a los seis estados reales. Los sensores no afectan su realimentación.':'Solo se miden α, θ y ψ. El estimador reconstruye velocidades usando mediciones y el comando conocido.'}</p>{config.observer==='filtered'&&<Numeric label="Filtro de velocidad" value={config.filterHz} min={.1} max={25} unit="Hz" onChange={v=>value('filterHz',v)}/>} {config.observer==='luenberger'&&<><Numeric label="Rapidez del observador" value={config.observerSpeed} min={.1} max={30} onChange={v=>value('observerSpeed',v)}/><Numeric label="Equilibrio del observador" value={config.trim} min={-60} max={60} step={1} unit="°" onChange={v=>value('trim',v)}/><p className="info-note">Observador lineal local: compara cerca de 15° antes de exigir la trayectoria completa.</p></>}{config.observer==='ekf'&&<><Numeric label="Escala Q del EKF" value={config.ekfQ} min={.001} max={10} step={.01} onChange={v=>value('ekfQ',v)}/><div className="section-label">R DEL EKF · DESVIACIÓN SUPUESTA [°]</div>{listArray('ekfR',['R α','R θ','R ψ'],5,.001,.05)}<p className="info-note">Q y R ajustan el estimador. No modifican el ruido físico de los sensores.</p></>}</>}
    {tab==='comp'&&<>{['compensateDeadzone','compensateFriction','compensateDelay'].map(k=><Toggle key={k} label={effectLabels[k]} checked={config.flags[k]} onChange={v=>edit(c=>{c.flags[k]=v;})}/>)}<p className="info-note">Las compensaciones usan parámetros nominales. Puedes activarlas aunque la planta no presente ese efecto y estudiar el exceso de compensación.</p><p className="info-note">El predictor mantiene constante la última entrada conocida. Su mejora no está garantizada.</p></>}
    <div className="advanced-toggle"><Toggle label="Opciones avanzadas" checked={advanced} onChange={setAdvanced}/></div>{advanced&&<><Numeric label="Paso de integración" value={config.dt} min={.005} max={.05} step={.005} unit="s" onChange={v=>value('dt',v)}/><Numeric label="Semilla" value={config.seed} min={0} max={10000} step={1} onChange={v=>value('seed',v)}/><details><summary>Condición inicial [° y °/s]</summary>{listArray('initial',['α inicial','α̇ inicial','θ inicial','θ̇ inicial','ψ inicial','ψ̇ inicial'],60,-60,.5)}</details><p className="muted">Arquitectura, observador, modelo, condición inicial, semilla y Δt inician una corrida nueva.</p></>}
   </aside>
  </div>
  <section className="evidence card"><div className="evidence-heading"><div><span className="eyebrow">03 · RESULTADOS</span><h2>Del movimiento a la evidencia</h2></div><span className="badge">{rows.length.toLocaleString()} muestras · {eventCount} cambios</span></div><div className="metrics">{[['RMSE elevación',metrics.rmse[0],'°'],['RMSE yaw',metrics.rmse[1],'°'],['Error estimación ψ',metrics.estimation[4],'°'],['Saturación',metrics.saturation,'%'],['Esfuerzo ∫u²dt',metrics.effort,'']].map(([label,v,unit])=><div key={String(label)}><span>{label}</span><strong>{Number(v).toFixed(2)}<small>{unit}</small></strong></div>)}</div><Charts rows={rows} runs={compared} cursor={cursor} onCursor={v=>{setRunning(false);setFollow(false);setCursor(v);}}/>{!follow&&<button className="text-button" onClick={()=>setFollow(true)}>Volver al último instante</button>}{metrics.waypoints.length>0&&<details><summary>Error al llegar a cada punto</summary><table><thead><tr><th>Punto</th><th>Tiempo [s]</th><th>Error α [°]</th><th>Error ψ [°]</th></tr></thead><tbody>{metrics.waypoints.map((p,i)=><tr key={i}><td>{p.point}</td><td>{p.t.toFixed(1)}</td><td>{p.error[0].toFixed(3)}</td><td>{p.error[1].toFixed(3)}</td></tr>)}</tbody></table></details>}</section>
  <section className="experiments card"><div className="evidence-heading"><div><span className="eyebrow">04 · COMPARAR Y REPRODUCIR</span><h2>Tu banco de experimentos</h2></div><div className="export-actions"><button onClick={()=>download('experimento-helicoptero.json',JSON.stringify(experiment(),null,2))}>↓ JSON</button><button onClick={csv}>↓ CSV</button><button onClick={()=>file.current?.click()}>Importar</button><button onClick={()=>void share()}>↗ Compartir</button></div></div><input ref={file} hidden type="file" accept=".json" onChange={async e=>{try{const f=e.target.files?.[0];if(f)await load(JSON.parse(await f.text()));}catch(err){setError(String(err));}e.target.value='';}}/><div className="save-row"><input aria-label="Nombre de la corrida" placeholder="Nombre de la corrida, p. ej. Sin zona muerta" value={runName} onChange={e=>setRunName(e.target.value)}/><button className="primary" onClick={()=>void save()}>Guardar corrida</button></div><p className="muted">Guardado local en este navegador. JSON conserva configuración y cambios temporizados; CSV contiene las señales. Marca corridas para superponerlas.</p>{runs.length? <div className="table-scroll"><table><thead><tr><th>Comparar</th><th>Corrida</th><th>RMSE α</th><th>RMSE ψ</th><th>Saturación</th><th>Esfuerzo</th><th>Acciones</th></tr></thead><tbody>{runs.map(run=><tr key={run.id}><td><input type="checkbox" aria-label={'Comparar '+run.name} checked={selected.includes(run.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,run.id]:old.filter(id=>id!==run.id))}/></td><td>{run.name}</td><td>{run.metrics.rmse[0].toFixed(2)}°</td><td>{run.metrics.rmse[1].toFixed(2)}°</td><td>{run.metrics.saturation.toFixed(1)}%</td><td>{run.metrics.effort.toFixed(2)}</td><td><button onClick={()=>void load(run.experiment)}>Reproducir</button><button aria-label={'Eliminar '+run.name} onClick={async()=>{await storage('delete',run.id);setRuns(old=>old.filter(r=>r.id!==run.id));setSelected(old=>old.filter(id=>id!==run.id));}}>×</button></td></tr>)}</tbody></table></div>:<div className="empty">Guarda tu primera corrida y cambia una sola condición para comparar.</div>}</section>
  <footer><span>HELICÓPTERO 3 GDL · LABORATORIO DE CONTROL</span><span>Ángulos en grados · cálculo interno en radianes · RK4 a {(1/config.dt).toFixed(0)} Hz</span></footer>
 </main>;
}
